### ISSUE TITLE
addon conflicts with Bagnon Equipment 2

### ISSUE THREAD

**Issue by lucianahanan** [GoldpawsStuff/Bagnon_BoE#1]
Your addon doesn't work together with the bagnon equipment which puts a tiny set icon over gear in bag.

I would like to have they working together, could you make a change to acomplish that? Maybe a smaller font, or another overlay layer ( if that's even possible ) or something.

**Comment by lucianahanan** [comment]
Also the dev from bagnon equipment 2 is not responding, maybe you could take over his addon just to have all 3 compatible would be wonderful :)

**Comment by Goldpaw** [comment]
Well I can't take over somebody else's addon, would take a looooot of time of inactivity, and it still wouldn't be mine to keep. 

But I can take a look at it and see if I can make mine work better with it. :)

**Comment by lucianahanan** [comment]
Also, I found another addon that have many functions in one, BoE, ilevel, etc.. That one is named Bagnon_ItemInfo. and worked with bagon equipment with no conflicts. Maybe you could take a look there to see the code differences ;)

**Comment by Goldpaw** [comment]
Well that's my addon too, so I'm kind aware of both that and your report on it already! :D

**Comment by lucianahanan** [comment]
aaah sorry, I'm very methodic and I like to put each issue to where it belong as a reminder to the coder, even if it's the same, I use to handle several different projects at once and I know how easy is to forget one :)

**Comment by lucianahanan** [comment]
By the way, I posted a suggestion/issue on the iteminfo place.  I could keep editing the lua file, but If you made it native, It would one less addon tweak to make on every patch  ; )

**Comment by Goldpaw** [comment]
> aaah sorry, I'm very methodic and I like to put each issue to where it belong as a reminder to the coder, even if it's the same, I use to handle several different projects at once and I know how easy is to forget one :)

Hey, nothing to apologize for! That's the right way to do it. One issue report per actual issue. Otherwise we'll have chaos, mayhem and total anarchy! :laughing:

**Comment by Minoz794** [comment]
Hello, does not work with the game in French, would it be possible to fix it?

**Comment by Goldpaw** [comment]
Yes, I can. But this is an old report about something completely different, so I'm closing this issue and opening a new one about this problem. The new issue is here: #7
