### ISSUE TITLE
Bagnon 10.0.11 broke things on your end

### ISSUE THREAD

**Issue by lowpita** [GoldpawsStuff/Bagnon_BoE#16]
Hey. Got these errors as of today's bagnon 10.0.11 release which prevent your bagnon_boe and bagnon_itemlevel addons from working properly (info is not displayed on the icons anymore): 

8x Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)
[string "=[C]"]: ?
[string "@Bagnon_BoE/main.lua"]:96: in function `update'
[string "@Bagnon_BoE/dispatcher.lua"]:76: in function <Bagnon_BoE/dispatcher.lua:74>
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@BagBrother/addons/core/classes/item.lua"]:128: in function <...rfaceBagBrother/addons/core/classes/item.lua:123>
[string "=[C]"]: in function `Show'
[string "@BagBrother/addons/core/classes/item.lua"]:42: in function <...rfaceBagBrother/addons/core/classes/item.lua:34>
[string "@Bagnon_Masque/Bagnon_Masque.lua"]:37: in function <Bagnon_Masque/Bagnon_Masque.lua:36>
[string "=(tail call)"]: ?
[string "@BagBrother/addons/core/classes/itemGroup.lua"]:124: in function `func'
[string "@BagBrother/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = "Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)"

12x Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)
[string "=[C]"]: in function `GetBagItem'
[string "@Bagnon_ItemLevel/main.lua"]:92: in function `update'
[string "@Bagnon_BoE/dispatcher.lua"]:76: in function <Bagnon_BoE/dispatcher.lua:74>
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@BagBrother/addons/core/classes/item.lua"]:128: in function <...rfaceBagBrother/addons/core/classes/item.lua:123>
[string "=[C]"]: in function `Show'
[string "@BagBrother/addons/core/classes/item.lua"]:42: in function <...rfaceBagBrother/addons/core/classes/item.lua:34>
[string "@Bagnon_Masque/Bagnon_Masque.lua"]:37: in function <Bagnon_Masque/Bagnon_Masque.lua:36>
[string "=(tail call)"]: ?
[string "@BagBrother/addons/core/classes/itemGroup.lua"]:124: in function `func'
[string "@BagBrother/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = "Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)"

**Comment by Mithras2801** [comment]
I have little same error

29x Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)
[string "=[C]"]: ?
[string "@Bagnon_BoE/main.lua"]:96: in function `update'
[string "@Bagnon_BoE/dispatcher.lua"]:76: in function <Bagnon_BoE/dispatcher.lua:74>
[string "=[C]"]: in function `Update'
[string "@BagBrother/addons/core/classes/item.lua"]:128: in function <...rfaceBagBrother/addons/core/classes/item.lua:123>
[string "=[C]"]: in function `Show'
[string "@BagBrother/addons/core/classes/item.lua"]:42: in function <...rfaceBagBrother/addons/core/classes/item.lua:34>
[string "=(tail call)"]: ?
[string "@BagBrother/addons/core/classes/itemGroup.lua"]:124: in function `func'
[string "@BagBrother/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = "Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)"

**Comment by lowpita** [comment]
Fixed on the latest update. Thank you.
