### ISSUE TITLE
BoE label not working on white/grey items

### ISSUE THREAD

**Issue by zeenk** [GoldpawsStuff/Bagnon_BoE#19]
Sorry for some reason I had the Ignore updates for this addon enabled in CurseApp, but found a bug with 2.0.59-Release version that grey/white items doesn't seem to work even for items that you can mog. this is on my DH and a BoE leather helm.
![2023-05-16_08-48-13](https://github.com/GoldpawsStuff/Bagnon_BoE/assets/68170439/86e66f47-73b3-4f07-91d2-5d2050d9df7a)

**Comment by Goldpaw** [comment]
Fixed
