### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zerocool145** [GoldpawsStuff/Bagnon_BoE#2]
apparently the addon conflicts with another addon
[Bagnon Boe.txt](https://github.com/AzeriteTeam/Bagnon_BoE/files/3995256/Bagnon.Boe.txt)

**Comment by Goldpaw** [comment]
This is the same bug as on our itemlevel plugin. They changed something in the backend on the most recent version, and it's affecting all the plugins it seems. I'll look into it. 

It's not a conflict, btw. "WildPants" is just the name of the libraries Bagnon is using to run certain things.

**Comment by dennovoselskiy** [comment]
It works like issue with Bagnon_ItemLevel [#3](https://github.com/AzeriteTeam/Bagnon_ItemLevel/pull/3) or you can use my lua 
[main](https://github.com/dennovoselskiy/Stress_Daun.git)

**Comment by Goldpaw** [comment]
Fixed
