### ISSUE TITLE
Cant Read text and cant see or disable to organize how I choose

### ISSUE THREAD

**Issue by Fight4freeTech** [GoldpawsStuff/Bagnon_BoE#3]
I cant see Bagnon BOE and have to squint and get too close to screen to make it visible...
one day I as I switched my characters after buying new bags all my BOE text on that character was white and very visible (*readable)
... the next time I logged on to that character it was all gone (*back to greens, blues, and purples)

I want to:
be able to see BOE and then disable it by choice 
             so I can see the required item level so I know who to send it to or how to organize it in my bank and guild bank... 

-and-

I want to either:
change BOE text to white *any color by choice  -or- *add a shadow -or- *have a filter behind lettering
                     to make it more visible and distinct from the item or from the border
                     * border blurs in with BOE text and so BOE is too hard to read for me    
         -and play and use both addons either by disabling or having a new option in your addon-
in order organize my bags 
so I tried to get Required level addon to work also
               but I couldn't do either

I have tried:
disable Required Level - and play with BOE
disable Item Info - and play with BOE
disable Item Level - and play with BOE
( * all individually)
( * in groups of 2)
( * one of each left enabled) - and play with BOE
( * all disabled at the same time)
( * reloading )
( * not reloading but logging out and back in...)
( * not reloading but exiting game and starting up again...)
             ** and all enabled at the same time

but couldn't get your addon to show back up in white lettering at all ...

Any option to change color or make text more visible would be nice
** I just cant see without pressing my face to the screen cause the colors all blur together
** even adding a filter or shading option may help
** and I would like to order/organize my bag by required level so too!
It's your addon and I do appreciate it much, so however you want to do it...

I play retail and have these addons

Bagnon_BOE
Bagnon_Currencies (*disabled)
Bagnon_Garbage
Bagnon_ItemInfo
Bagnon Item Level
Bagnon Required Level
Bagnon Scrap

(*) original Bagnon package
Bagnon Void Storage
Bagnon Guild Bank
Bagnon Config
Bagnon
BagBrother

Thank You for a great addition to addons hope to see it working soon!

**Comment by Goldpaw** [comment]
So to sum it up this is a feature request to have the BoE text white, instead of rarity colored? :)

Yeah, I can probably work in some sort of setting for that. 

But, uh, Bagnon_ItemInfo overrides Bagnon_BoE, Bagnon_Garbage and Bagnon_ItemLevel. Basically the last 3 simply never loads when you have enabled Bagnon_ItemInfo. So any combination of ItemInfo and any of my other bagnon plugins, means only iteminfo is loaded. 

I guess I'll have to add this option to both Bagnon_BoE and Bagnon_ItemInfo, then.

**Comment by Fight4freeTech** [comment]
Wow thanks a lot! I didnt expect a response this quick. Thank you and have a good rest of the year!

**Comment by Goldpaw** [comment]
Just a tiny status update here, so those following this won't think I've forgotten about it:

I've more or less finished the feature, and working on syncing it between my different bagnon plugins and wow versions now! I've added chat commands in Bagnon_Boe, Bagnon_ItemLevel and Bagnon_ItemInfo to disable rarity coloring. I didn't have any BoEs in my bag while testing this, so my demonstration screenshots below are only for the itemlevel. 

Now all it requires is to make sure I've weeded out most of the bugs I always seem to include in new things, and upload it! Can't guarantee it'll be today, but one of the upcoming days it'll all be ready and done.

I'll of course update this issue when it's live, as well as update the addon descriptions with the new chat commands.

![Screenshot from 2021-12-12 19-29-44](https://user-images.githubusercontent.com/6476535/145725130-b77d8dca-43d9-4cfe-8b8a-89472112be03.png)

![Screenshot from 2021-12-12 19-29-28](https://user-images.githubusercontent.com/6476535/145725131-f616bbf8-8957-468d-a5ab-a781799a2fe8.png)

**Comment by Goldpaw** [comment]
So "coming very soon", in other words :D

**Comment by Goldpaw** [comment]
Added in the latest version. To toggle coloring of BoE texts, use:
(the commands are the bold part, not the rest, that's just my comments!)

* **/boe enable color** _- Enable rarity coloring of text._  
* **/boe disable color** _- Disable rarity coloring of text._  

Or if you're using the Bagnon_ItemInfo addon, the commands for the same in its latest versions uploaded today, are: 

* **/bif enable color** _- Enable rarity coloring of text._  
* **/bif disable color** _- Disable rarity coloring of text._
