### ISSUE TITLE
Addon displays BOE when item soulbound

### ISSUE THREAD

**Issue by Rorthron1** [GoldpawsStuff/Bagnon_BoE#6]
For a while now in TBC, the addon has continued to show BOE even when an item is soulbound. 
Screen shot attached
![image](https://user-images.githubusercontent.com/100441526/155774113-3e3f445c-67c3-413d-81a6-960669558c43.png)
All the items in my bag showing as BOE are in fact soulbound. If I get a proper BOE, it also shows as BOE. 
I've tested this in two accounts on two different PCs and the result is the same.

**Comment by Goldpaw** [comment]
Hopefully fixed in 1.0.38-Release. I reverted to an older version of soulbound detection for the classic clients.

**Comment by Rorthron1** [comment]
Seems to be better now, thanks.
